# Generated by Django 5.2.15 on 2026-06-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
        ('stagiaires', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom/Libellé descriptif de la tâche', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la tâche', null=True)),
                ('realisee', models.BooleanField(default=False, help_text='La tâche est-elle réalisée ?')),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='a_faire', help_text='Statut actuel de la tâche', max_length=20)),
                ('priorite', models.CharField(choices=[('haute', 'Haute'), ('moyenne', 'Moyenne'), ('faible', 'Faible')], default='moyenne', help_text='Priorité de la tâche', max_length=20)),
                ('date_limite', models.DateField(help_text='Échéance de réalisation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('assignee_a', models.ForeignKey(blank=True, help_text='Stagiaire assigné à la tâche', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='stagiaires.stagiaire')),
                ('projet', models.ForeignKey(help_text='Projet parent de la tâche', on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-date_limite', '-priorite'],
                'indexes': [models.Index(fields=['projet', 'statut'], name='taches_tach_projet__9c8c2e_idx'), models.Index(fields=['assignee_a', 'statut'], name='taches_tach_assigne_6dbb11_idx')],
            },
        ),
    ]
