# Generated by Django 5.2.15 on 2026-06-16 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stagiaires', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_entree', models.TimeField(blank=True, null=True)),
                ('heure_sortie', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('ferie', 'Jour Férié')], default='present', max_length=20)),
                ('justification', models.TextField(blank=True, null=True)),
                ('est_justifiee', models.BooleanField(default=False)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='stagiaires.stagiaire')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'unique_together': {('stagiaire', 'date')},
            },
        ),
    ]
