# Generated by Django 5.2.15 on 2026-07-08 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presences', '0001_initial'),
        ('stagiaires', '0004_departement_stagiaire_departement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severite', models.CharField(choices=[('critique', 'Critique'), ('avertissement', 'Avertissement'), ('info', 'Info')], default='info', max_length=20)),
                ('statut', models.CharField(choices=[('non-lue', 'Non lue'), ('lue', 'Lue'), ('resolue', 'Résolue')], default='non-lue', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('absence', 'Absence'), ('retard', 'Retard'), ('conge', 'Congé')], max_length=20)),
                ('date', models.DateField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en-attente', 'En attente'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], default='en-attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_rh', models.TextField(blank=True, null=True)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='stagiaires.stagiaire')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Justification',
                'verbose_name_plural': 'Justifications',
                'ordering': ['-date_demande'],
            },
        ),
    ]
