# Generated by Django 5.2.15 on 2026-07-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presences', '0002_alerte_justification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justification',
            name='commentaire_rh',
        ),
    ]
