# Generated by Django 5.2.15 on 2026-06-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecole', models.CharField(max_length=200)),
                ('formation', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('cv_path', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('convention_validee', models.BooleanField(default=False)),
                ('stage_valide', models.BooleanField(default=False)),
                ('absences_nj_count', models.IntegerField(default=0)),
                ('rapport_final_depose', models.BooleanField(default=False)),
                ('rapport_final_statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
            ],
        ),
    ]
