# Generated by Django 5.2.15 on 2026-06-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='statut',
        ),
    ]
