# Generated by Django 5.2.15 on 2026-06-19 16:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stagiaires', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_path', models.FileField(help_text='Fichier PDF du rapport final', upload_to='rapports_finaux/')),
                ('date_depot', models.DateField(auto_now_add=True)),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('commentaire_rh', models.TextField(blank=True, help_text='Commentaire de validation ou refus par les RH', null=True)),
                ('stagiaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport_final', to='stagiaires.stagiaire')),
                ('valide_par', models.ForeignKey(blank=True, help_text='RH ou Admin ayant validé le rapport', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_finaux_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport final de stage',
                'verbose_name_plural': 'Rapports finaux de stage',
            },
        ),
        migrations.CreateModel(
            name='RapportJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rapport', models.DateField(default=datetime.date.today)),
                ('taches_realisees', models.JSONField(blank=True, help_text="Liste JSON des tâches terminées aujourd'hui", null=True)),
                ('taches_en_cours', models.JSONField(blank=True, help_text='Liste JSON des tâches non terminées', null=True)),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire libre du stagiaire', null=True)),
                ('depose', models.BooleanField(default=False, help_text='Indique si le rapport a été soumis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_journaliers', to='stagiaires.stagiaire')),
            ],
            options={
                'verbose_name': 'Rapport journalier',
                'verbose_name_plural': 'Rapports journaliers',
                'ordering': ['-date_rapport'],
                'unique_together': {('stagiaire', 'date_rapport')},
            },
        ),
    ]
