# Generated by Django 5.2.15 on 2026-07-13 16:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapportfinal',
            name='fichier_path',
        ),
        migrations.AddField(
            model_name='rapportfinal',
            name='fichier',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fichier'),
        ),
    ]
