# Generated by Django 5.2.15 on 2026-06-15 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stagiaires', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du projet', max_length=200)),
                ('description', models.TextField(help_text='Description détaillée du projet')),
                ('date_debut', models.DateField(help_text='Date de démarrage du projet')),
                ('date_limite', models.DateField(help_text='Échéance du projet')),
                ('etat', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('en_retard', 'En retard')], default='en_cours', help_text='État actuel du projet', max_length=20)),
                ('pourcentage_avancement', models.IntegerField(default=0, help_text="Pourcentage d'avancement calculé automatiquement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, help_text='Responsable du projet (généralement RH ou Manager)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_responsable', to=settings.AUTH_USER_MODEL)),
                ('stagiaires', models.ManyToManyField(blank=True, help_text='Stagiaires assignés au projet', related_name='projets', to='stagiaires.stagiaire')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
    ]
